# Generated by Django 4.2.7 on 2023-11-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(default='cover_default.png', upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
